class locators:
    textbox_email_xpath = '/html/body/div[1]/div/div[2]/div[2]/div[2]/div[2]/div/div/form/div[1]/input'
    textbox_password_xpath = '/html/body/div[1]/div/div[2]/div[2]/div[2]/div[2]/div/div/form/div[2]/input'
    button_sign_in_xpath = '/html/body/div[1]/div/div[2]/div[2]/div[2]/div[2]/div/div/form/input[3]'
    """textbox_email_xpath = '//input[@id = "signInFormUsername"]'
    textbox_password_xpath = '//input[@id = "signInFormPassword"]'
    button_sign_in_xpath = '//input[@name = "signInSubmitButton"]'"""
    button_Logged_in_user_xpath = "//a[@id='top-bar__user__menu']/i"
    button_sign_out_xpath = "//span[text() = 'Sign Out']"
    button_dataset_selection_Ok_xpath = '//button[contains(text(), "OK")]'
    banner_Dataset_loading_xpath = '//div[contains(text(), "Dataset is")]'
    header_dataset_comparison_id = "heading__dataset-name"

    Header_Search = "search-bar__search"
    Edit_button = '//button[text()= "Edit"]'

    side_nav_bar_element_xpath = '//a[contains(text(), "Dataset Info"])'
    nav_bar_Ito_Logo_xpath = '//img[@alt="Ito Edit"]'
    menu_collapse_button_xpath = '//i[@class= "far fa-angle-double-left"]'
    menu_Dataset_Info_xpath = '//a[contains(text(), "Dataset Info")]'
    menu_Situations_xpath = '//a[contains(text(), "Situations")]'
    menu_Map_xpath = '//a[contains(text(), "Map")]'
    menu_Warnings_xpath = '//div[contains(text(), "Warnings")]'
    menu_Warnings_expand_button_xpath = '//div[text() = "Warnings"]/following::i[1]'
    menu_Anomalies_xpath = '//a[contains(text(), "Anomalies")]'
    menu_Interventions_xpath = '//div[contains(text(), "Interventions")]'
    menu_Interventions_expand_button_xpath = '//div[contains(text(), "Interventions")]/following::i[1]'
    menu_Current_Interventions_xpath = '//a[contains(text(), "Current Interventions")]'
    menu_Mass_Interventions_xpath = '//a[contains(text(), "Mass Interventions")]'
    menu_Rule_Interventions_xpath = '//a[contains(text(), "Rule Interventions")]'
    menu_Warning_Descriptions_xpath = '//a[contains(text(), "Warning Descriptions")]'
    menu_Ito_Objects_xpath = '//a[contains(text(), "Ito Objects")]'
    menu_Service_Links_xpath = '//a[contains(text(), "Service Links")]'
    menu_Quality_Dimensions_xpath = '//a[contains(text(), "Quality Dimensions")]'
    menu_Intervention_Map_Tool_xpath = '//a[contains(text(), "Intervention Map Tool")]'
    dataset_info_header = '//div[contains(text(), "Dataset Info")]'
    situations_header = '//div[contains(text(), "Situations")]'
    mapbox_logo = '//a[@class="mapboxgl-ctrl-logo"]'
    header_anomalies = '//div[contains(text(), "Anomalies")]'
    header_warning_descriptions = '//div[contains(text(), "Warning Descriptions")]'
    header_current_interventions = '//div[@id="heading__entity-name" and text() = "Current Interventions"]'
    header_mass_interventions = '//div[@id="heading__page-name" and text() = "Mass Interventions"]'
    header_rule_interventions = '//div[@id="heading__entity-name" and text() = "Rule Interventions"]'
    Summary_Comparison_xpath = '//a[@title = "Comparison"]'
    Summary_Missing_xpath = '//a[@title = "Missing"]'
    Summary_New_xpath = '//a[@title = "New"]'
    Summary_Warnings_xpath = '//a[@title = "Warnings"]'
    Summary_Statistics_xpath = '//a[@title = "Statistics"]'
    Summary_Summary_Metrics_xpath = '//a[@title = "Summary Metrics"]'
    Summary_Dataset_Operators_xpath = '//a[@title = "Dataset  Operators"]'
    Warnings_West_Midlands_Journeys = '//td[text() = "West Midlands"]/following::div[2]'
    Warnings_West_Midlands_Journeys_Bezier_Direction = '//td[text() = "West Midlands"]/following::a[1]'
    West_Midlands_Warnings_header = '//div[@id="heading__entity-name" and text() = "West Midlands"]'
    Warnings_Results_for_Bezier_direction_banner = '//div[text() = "Results for Bezier direction "]'

    dataset_info_Source_Files = '//a[contains(text(), "Source Files")]'

    Table = '//table'
    Warning_Definitions_Bezier_opposite = '//dt[text() = "Bezier opposite"]'
    link_Privacy_Policy_xpath = '//a[text() = "Privacy Policy"]'
    link_Licences_xpath = '//a[text() = "Licences"]'
    link_Glossary_xpath = '//a[text() = "Glossary"]'
    privacy_policy_Ito_World_img_xpath = '//img[@alt = "ITO World"]'
    privacy_policy_header = '//h1[text() = "Privacy Policy"]'
    Licences_header = '//div[text() = "Licences"]'
    Licences_MIT_Licences_text = '//pre[contains(text(), "The MIT License (MIT)")]'
    Glossary_header = '//div[text() = "Glossary"]'
    Glossary_Journey_Association_link = '//a[@title = "Journey Association"]'
    Glossary_Journey_Association_table_header = '//div[@id = "journey_association"]'
    Scroll_to_top_button = "//div[@id='backToTop']/i"
    Glossary_Access_Space_link = '//a[@title = "Access Space"]'

    header_Line = '//div[@title = "Line"]'
    First_link_in_search_results = '//span[text()="Name"]/following::a[1]'
    Entity_Id_value = '//label[text() = "Entity Id"]/following::div[1]'
    header_Stop = '//div[text() = "Stop"]'

    Mini_Map_Canvas = '//canvas'
    Mini_Map_Resize_minus_button = '//div[@id="minimap__decrease-map-size"]'
    Mini_Map_Resize_plus_button = '//div[@id="minimap__increase-map-size"]'
    Mini_Map_Reset_button = '//div[@id="minimap__reset-map"]'
    Mini_Map_Hide_button = '//i[@class = "far fa-angle-double-right"]'
    Mini_Map_Mapbox_Logo = '//a[@class = "mapboxgl-ctrl-logo"]'
    Mini_Map_Recover_button = '//div[@id="minimap__show_map"]'
    Mini_Map_See_in_button = '//button[@id = "minimap__see-in"]'
    Mini_Map_See_in_Google_Maps_option = '//a[contains(text(), "Google Maps")]'
    Mini_Map_See_in_ITO_Map_option = '//a[contains(text(), "ITO Map Browser v2")]'
    Mini_MapSeein_ITOMap_MapBoundary = '//div[@class = "ito_main_content"]'
    Mini_Map_mapbox = '//*[@id="map-container"]/mgl-map/div/div[3]/div[3]/div/a'

    Line_Service_Patterns_Tab = '//a[contains(text(), "Service Patterns")]'
    Line_Anomalies_Tab = '//a[contains(text(), "Anomalies")]'
    Line_Warnings_Tab = '//a[contains(text(), "Warnings")]'
    Line_Interventions_Tab = '//a[contains(text(), "Interventions")]'
    Line_SP_Service_Patterns_header = '//div[text() = "Service Patterns"]'
    Line_Anomalies_Journey_Count_Baseline_header = '//div[text() = "Journey Count Baseline"]'
    Line_Warnings_All_button = '//a[text() = "All"]'
    Line_Interventions_Model_Object_Logs_header = '//div[text() = "Model Object Logs"]'

    Stop_Lines_Tab = '//a[@class = "nav-link unselectable" and text() = "Lines"]'
    Stop_Destinations_Tab = '//a[@class = "nav-link unselectable" and text() = "Destinations"]'
    Stop_Links_Tab = '//a[@class = "nav-link unselectable" and text() = "Links"]'
    Stop_Pattern_Departures_Tab = '//a[@class = "nav-link unselectable" and text() =  "Pattern Departures"]'
    Stop_Chron_Departures_Tab = '//a[@class = "nav-link unselectable" and text() = "Chron Departures"]'
    Stop_Export_Info_Tab = '//a[@class = "nav-link unselectable" and text() =  "Export Info"]'
    Stop_Warnings_Tab = '//a[@class = "nav-link unselectable" and text() =  "Warnings"]'
    Stop_Interventions_Tab = '//a[@class = "nav-link unselectable" and text() =  "Interventions"]'

    header_Operator = '//div[text() = "Operator"]'
    Operator_Warnings_Tab = '//a[@class = "nav-link unselectable" and text() = "Warnings"]'
    Operator_Interventions_Tab = '//a[@class = "nav-link unselectable" and text() = "Interventions"]'
    Operator_Operator_Journey_Counts_Tab = '//a[@class = "nav-link unselectable" and text() = "Operator Journey Counts"]'
    Operator_Line_Journey_Counts_Tab = '//a[@class = "nav-link unselectable" and text() = "Line Journey Counts"]'
    Gantt_Update_Charts_button = '//button[@id = "filter_btn"]'
    Gantt_chart_cell = '//div[@class = "gantt-chart__cell gantt-chart__cell--journey-count ng-star-inserted"]'

    Text_Colour_Select_Tab = '//label[text() = "Text Colour"]/following::input[2]'
    Text_Colour_Scroll = '//label[text() = "Text Colour"]/following::div[15]'
    SaveSuccessPopUp = '//div[@id = "toast-container"]'
    DeleteSuccessPopUp = '//div[@id = "toast-container"]'
    Text_Colour_Select_Enter = '//label[text() = "Text Colour"]/following::div[7]'
    Save_button = "(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[1]"
    Op_Colour_Select_Tab = '//label[text() = "Colour"]/following::input[2]'
    Op_Colour_Scroll = '//label[text() = "Colour"]/following::div[15]'
    Op_Colour_Select_Enter = '//label[text() = "Colour"]/following::div[7]'
    Op_Colour_DeleteBin = '//label[text() = "Colour"]/following::i[1]'

